### ISSUE TITLE
gb_reviews isn't filtering by ID

### ISSUE THREAD

**Issue by alexjudeking** [detroyejr/giantbomb#1]
Not sure what I'm doing wrong but the gb_reviews method isn't filtering the results by the ID of the game input. Trying to get the score of Hollow Knight (ID 48412) but it's just giving me the most recent entry.

gb_reviews(
    n = 1,
    filter= "id:48412",
    sort = "date_added:desc",
    field_list = c("score", "id")
    )

Best Regards

**Comment by detroyejr** [comment]
Did you find a solution to your problem?

**Comment by alexjudeking** [comment]
Yes I did!
Sorry for the confusion

**Comment by detroyejr** [comment]
Would you mind posting the code snippet that worked? I took a look, but it's been a while since I've looked at their API. Thanks!

**Comment by alexjudeking** [comment]
Sure thing, the actual issue was that I was trying to search for a game ID
that Giant Bomb didn't have a review for. Changed the game ID to a game
that they did have a review for.

Cheers

gb_reviews(
    n = 1,
    filter= "game:36765",
    field_list = c("score", "id","game")
  )
